### ISSUE TITLE
how to

### ISSUE THREAD

**Issue by lARSHADl** [cadavre/iq_notify#3]
how do i add  it in home assistant do i need to install it.. ?

**Comment by wtadler** [comment]
See [here](https://community.home-assistant.io/t/iqnotify-smart-notification-grouping-only-home-only-away-just-left-etc/123743). @cadavre, should those instructions be in the repo README as well?

**Comment by cadavre** [comment]
There is no way to install it with hassio addon, you must have access to your filesystem and copy repository contents into `iq_notify` of your HASS home's `custom_components`.

I updated the README.
